const PDFDocument = require("pdfkit-table");

/**
 * Generates a PDF Report
 * @param {Object} reportDetails - Metadata of the report
 * @param {Array} data - Array of objects to be displayed in the table
 * @returns {Promise<Buffer>} - Resolves to the PDF buffer
 */
const generatePDFReport = async (reportDetails, data) => {
    return new Promise((resolve, reject) => {
        const doc = new PDFDocument({ margin: 30, size: "A4" });
        const buffers = [];

        doc.on("data", (chunk) => buffers.push(chunk));
        doc.on("end", () => resolve(Buffer.concat(buffers)));
        doc.on("error", (err) => reject(err));

        // --- Header ---
        doc.fontSize(20).text("IslingConnect Report", { align: "center" });
        doc.moveDown();
        doc.fontSize(14).text(`Department: ${reportDetails.department}`, { align: "left" });
        doc.text(`Period: ${reportDetails.period}`, { align: "left" });
        doc.text(`Date Range: ${new Date(reportDetails.startDate).toLocaleDateString()} - ${new Date(reportDetails.endDate).toLocaleDateString()}`, { align: "left" });
        doc.text(`Generated By: ${reportDetails.adminName}`, { align: "left" });
        doc.moveDown();

        // --- Summary Stats ---
        doc.fontSize(16).text("Summary Statistics", { underline: true });
        doc.moveDown(0.5);
        doc.fontSize(12);
        Object.entries(reportDetails.summary).forEach(([key, value]) => {
            doc.text(`${key}: ${value}`);
        });
        doc.moveDown();

        // --- Data Table ---
        doc.fontSize(16).text("Detailed Records", { underline: true });
        doc.moveDown();

        const table = {
            title: `Records for ${reportDetails.department}`,
            headers: [],
            rows: [],
        };

        // Configure table based on department
        if (reportDetails.department === "IT" || reportDetails.department === "PAT") {
            table.headers = ["Student", "Title", "Date", "Time", "Status"];
            table.rows = data.map(item => [
                String(item.studentName || "N/A"),
                String(item.title || "N/A"),
                new Date(item.date).toLocaleDateString(),
                String(item.time || "N/A"),
                String(item.status || "N/A")
            ]);
        } else if (reportDetails.department === "LostFound") {
            table.headers = ["Item (Cat)", "Type", "Location", "Uploader", "Reclaimer", "Date", "Status"];
            table.rows = data.map(item => [
                `${item.itemName} (${item.category})`,
                String(item.type || "N/A"),
                String(item.location || "N/A"),
                item.user ? `${item.user.username}\n${item.user.phone}` : "Anonymous",
                item.reclaimer ? `${item.reclaimer.username}\n${item.reclaimer.phone}` : "N/A",
                new Date(item.date).toLocaleDateString(),
                String(item.status || "N/A")
            ]);
        } else if (reportDetails.department === "StudentServices") {
            table.headers = ["Student Name", "Email", "Description", "Status", "Date"];
            table.rows = data.map(item => [
                String(item.studentName || "N/A"),
                String(item.studentEmail || "N/A"),
                String(item.description || "N/A"),
                String(item.status || "N/A"),
                new Date(item.createdAt).toLocaleDateString()
            ]);
        }

        doc.table(table, {
            prepareHeader: () => doc.font("Helvetica-Bold").fontSize(10),
            prepareRow: (row, i) => doc.font("Helvetica").fontSize(10),
        });

        // --- Footer ---
        const range = doc.bufferedPageRange();
        for (let i = range.start; i < range.start + range.count; i++) {
            doc.switchToPage(i);
            doc.fontSize(8).text(
                `Generated on ${new Date().toLocaleString()} - Page ${i + 1} of ${range.count}`,
                30,
                doc.page.height - 50,
                { align: "center" }
            );
        }

        doc.end();
    });
};

module.exports = { generatePDFReport };
